using Microsoft.Data.Sqlite;
using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Security.RightsManagement;
using System.Text;

namespace domainAnalyserSat
{
    public static class sessionRepo
    {
        //All db access lives here , avoid writing raw sql 



        //Insert one sssion row and return sqlite assigned ID


        public static long createSession(long userId, string name) //userId is foreign key linking the session to its original user 
        {
            //
            using SqliteConnection connection = Database.GetConnection();
            using SqliteCommand insert = new SqliteCommand(
                "INSERT INTO sessions (userId, name, createdAt) VALUES (@userId, @name, @createdAt);",
                connection



                );

            //map value into respective placeholders 
            insert.Parameters.AddWithValue("@userId", userId);
            insert.Parameters.AddWithValue("@name", name);
            insert.Parameters.AddWithValue("@createdAt", DateTime.UtcNow.ToString("o")); //timestamp stored in standard datetime (YYYY/MM/DD)

            //runs the inert and return the number of rows changed 
            insert.ExecuteNonQuery();

            using SqliteCommand idQuerey = new SqliteCommand("SELECT last_insert_rowid();", connection); //Sqlite function, returns id generated by most recent insert (same from userRepo)
            return (long)idQuerey.ExecuteScalar()!; //unbox the long and declare the value as non- null








        }







    }






}
