using Microsoft.Data.Sqlite;
using System;
using System.Collections.Generic;
using System.Net.Sockets;
using System.Text;

namespace domainAnalyserSat
{
    public static class UserRepo
    {
        //Check if the username is arleady taken - count how many rows match and return 
        public static bool UserNameExist(string username)
        {
            using SqliteConnection connection = Database.GetConnection();
            using SqliteCommand command = new SqliteCommand(
                "SELECT COUNT(*) FROM users WHERE username = @username;", connection);
            command.Parameters.AddWithValue("@username", username);

            long count = (long)command.ExecuteScalar()!;
            return count > 0;



        }

        //Create new user and assign user id 
        public static long CreateUser(string username, string passHash)
        {
            using SqliteConnection connection = Database.GetConnection();

            using SqliteCommand insert = new SqliteCommand(@"INSERT INTO users (username, passwordHash, createdAt)
                  VALUES (@username, @passwordHash, @createdAt);", connection);

            insert.Parameters.AddWithValue("@username", username);
            insert.Parameters.AddWithValue("@passwordHash", passHash);
            insert.Parameters.AddWithValue("@createdAt", DateTime.UtcNow.ToString("o")); //Claud - Use ISO 8601 format for UTC timestamp since sqlite has no dedciated data tpe
            insert.ExecuteNonQuery(); //run the insert 

            using SqliteCommand idQuerey = new SqliteCommand("SELECT last_insert_rowid();", connection); //Sqlite function, returns id generated by most recent insert 
            return (long)idQuerey.ExecuteScalar()!;



        }
        
        public static User? GetByUsername(string username) //username can return null
        {
            using SqliteConnection connection = Database.GetConnection();
            using SqliteCommand command = new SqliteCommand(
                "SELECT userId, username, passwordHash, createdAt, lastLogin FROM users WHERE username = @username;", connection);


            command.Parameters.AddWithValue("@username", username);

            using SqliteDataReader reader = command.ExecuteReader();
            if (!reader.Read()) //no rows returned, uer not ofund 
            {

                return null;


            }


            return new User
            {

                userId = reader.GetInt64(0), //ordinal 0 
                username = reader.GetString(1),
                passwordHash = reader.GetString(2),
                createdAt = DateTime.Parse(reader.GetString(3)),
                lastLogin = reader.IsDBNull(4) ? (DateTime?)null : DateTime.Parse(reader.GetString(3)) //claude helped with this line 

                    







            };
            
               

            //stamp last successful login time 








}
}
}

